webtalk_init -webtalk_dir C:/Users/Gia Duy/Documents/Basys3_project/Assignment_level_2/Assignment_level_2/Assignment_level_2.sim/sim_1/behav/xsim/xsim.dir/TB_keypadProc_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 12 00:16:24 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bad7d622-3144-428b-8dc1-b96fd4160d25" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "159ceb8f0d78446285d9da36ef9b2480" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "32" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1380 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5996_KB" -context "xsim\\usage"
webtalk_transmit -clientid 307726705 -regid "" -xml C:/Users/Gia Duy/Documents/Basys3_project/Assignment_level_2/Assignment_level_2/Assignment_level_2.sim/sim_1/behav/xsim/xsim.dir/TB_keypadProc_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Gia Duy/Documents/Basys3_project/Assignment_level_2/Assignment_level_2/Assignment_level_2.sim/sim_1/behav/xsim/xsim.dir/TB_keypadProc_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Gia Duy/Documents/Basys3_project/Assignment_level_2/Assignment_level_2/Assignment_level_2.sim/sim_1/behav/xsim/xsim.dir/TB_keypadProc_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
